# -*- coding: utf-8 -*-
"""dashboard_dados_imersao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WW38m5p-GAUCAdT3MKbB-KPab-HDfWmQ
"""

# Projeto Final - Imersão Dados com Python (Alura)
# Autor: Paulo Eduardo
# Descrição: Análise exploratória de dados com Python

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

df.head()

df.info()
df.describe()

df.isnull().sum()

df["gorjeta_percentual"] = (df["tip"] / df["total_bill"]) * 100

df.groupby("day")["tip"].mean().sort_values()

sns.barplot(data=df, x="day", y="tip")
plt.title("Gorjeta média por dia")
plt.show()

sns.scatterplot(data=df, x="total_bill", y="tip", hue="sex")
plt.title("Total da conta vs Gorjeta")
plt.show()

sns.boxplot(data=df, x="day", y="gorjeta_percentual")
plt.title("Distribuição da Gorjeta (%) por dia")
plt.show()

print("""
Conclusões:
- A gorjeta média varia conforme o dia da semana.
- Contas mais altas tendem a gerar gorjetas maiores.
- Existe variação no percentual de gorjeta entre os dias.
""")